export type JourneyIllustration = { src: string; alt: string; width: number; height: number };

const illustration = (id: string, alt: string, version = 1): JourneyIllustration => ({
  src: `/images/journeys/${id}-v${version}.webp`, alt: `${alt} — рисованная иллюстрация`, width: 1536, height: 1024,
});

// Explicit URL assignments: do not silently reuse a different destination's image.
export const journeyIllustrations: Record<string, JourneyIllustration> = {
  '/routes/mineralnye-vody-pyatigorsk': illustration('mineralnye-vody-pyatigorsk', 'Мама, дочь и бабушка с чемоданами у минивэна на фоне паркового Пятигорска'),
  '/routes/mineralnye-vody-nalchik': illustration('mineralnye-vody-nalchik', 'Компания с дорожными сумками у минивэна на фоне гор и озера близ Нальчика'),
  '/routes/voronezh-lipetsk': illustration('voronezh-lipetsk', 'Семья с чемоданами у минивэна на зелёной речной набережной Липецка'),
  '/routes/voronezh-tambov': illustration('voronezh-tambov', 'Семья и друзья с чемоданами у минивэна в осеннем Тамбове'),
  '/routes/novosibirsk-kemerovo': illustration('novosibirsk-kemerovo', 'Родители с детьми и чемоданами у минивэна на фоне речной панорамы Кемерова'),
  '/routes/krasnodar-anapa': illustration('krasnodar-anapa', 'Семья укладывает чемоданы в минивэн на фоне песчаного берега Анапы'),
  '/routes/krasnodar-gelendzhik': illustration('krasnodar-gelendzhik', 'Друзья с дорожными чемоданами у минивэна любуются бухтой Геленджика'),
  '/routes/mineralnye-vody-dombay': illustration('mineralnye-vody-dombay', 'Семья с багажом и лыжными чехлами у минивэна среди снежных гор Домбая'),
  '/routes/mineralnye-vody-kislovodsk': illustration('mineralnye-vody-kislovodsk', 'Старшая пара и дочь с чемоданами у минивэна среди парковой зелени Кисловодска'),
  '/routes/adler-roza-khutor': illustration('adler-roza-khutor', 'Семья у минивэна любуется горной долиной и канатной дорогой близ Розы Хутор'),
  '/routes/sochi-krasnaya-polyana': illustration('sochi-krasnaya-polyana', 'Друзья с чемоданами у минивэна на фоне горной долины Красной Поляны'),
  '/routes/simferopol-yalta': illustration('simferopol-yalta', 'Семья с багажом у минивэна на фоне моря и приморских склонов Ялты'),
  '/routes/simferopol-alushta': illustration('simferopol-alushta', 'Пара с дочерью и чемоданом у минивэна над приморской панорамой Алушты'),
  '/routes/simferopol-evpatoriya': illustration('simferopol-evpatoriya', 'Родители с двумя детьми и чемоданами у минивэна на морской набережной Евпатории'),
  '/routes/simferopol-feodosiya': illustration('simferopol-feodosiya', 'Пара и старшая пассажирка с дорожными сумками подходят к минивэну у морского города'),
  '/routes/simferopol-sudak': illustration('simferopol-sudak', 'Пара с чемоданами у минивэна на фоне бухты и крепостных стен Судака'),
  '/routes/simferopol-sevastopol': illustration('simferopol-sevastopol', 'Семья с багажом у минивэна рядом с морской панорамой Севастополя'),
  '/routes/rostov-sochi': illustration('rostov-sochi', 'Семья с чемоданами у светлого минивэна на фоне зелёного морского Сочи'),
  '/routes/rostov-adler': illustration('rostov-adler', 'Путешественники с дорожными сумками рядом с минивэном среди южной зелени Адлера'),
  '/routes/moskva-sochi': illustration('moskva-sochi', 'Семья с багажом выходит из минивэна у солнечного приморского пейзажа Сочи'),
  '/routes/kazan-ekaterinburg': illustration('kazan-ekaterinburg', 'Компания путешественников у минивэна на фоне городского пруда Екатеринбурга'),
  '/routes/moskva-spb': illustration('moskva-spb', 'Пассажиры с чемоданами у минивэна на фоне петербургской архитектуры и каналов'),
  '/routes/spb-moskva': illustration('spb-moskva', 'Семья с дорожными чемоданами рядом с минивэном на московской улице'),
  '/routes/moskva-voronezh': illustration('moskva-voronezh', 'Путешественники с багажом рядом с минивэном на фоне зелёного Воронежа'),
  '/routes/voronezh-moskva': illustration('voronezh-moskva', 'Семья с чемоданами у минивэна на фоне Москвы после поездки'),
  '/routes/moskva-kazan': illustration('moskva-kazan', 'Семья с дорожными вещами у минивэна среди узнаваемой архитектуры Казани'),
  '/routes/kazan-moskva': illustration('kazan-moskva', 'Пассажиры с чемоданами и минивэн на фоне вечерней Москвы'),
  '/routes/novosibirsk-omsk': illustration('novosibirsk-omsk', 'Компания с багажом рядом с минивэном на речной набережной Омска'),
  '/routes/moskva-tver': illustration('moskva-tver', 'Семья с дорожными чемоданами у светлого минивэна на фоне тихого исторического квартала Твери'),
  '/routes/volgograd-rostov': illustration('volgograd-rostov', 'Компания путешественников с багажом рядом с минивэном в тёплом южном Ростове-на-Дону'),
  '/routes/krasnodar-adler': illustration('krasnodar-adler', 'Семья с чемоданами прибывает на минивэне в зелёный приморский Адлер'),
  '/routes/moskva-nizhniy-novgorod': illustration('moskva-nizhniy-novgorod', 'Путешественники с багажом рядом с минивэном на фоне речного Нижнего Новгорода'),
  '/routes/yaroslavl-moskva': illustration('yaroslavl-moskva', 'Семья и чемоданы у минивэна на фоне московского городского пейзажа'),
  '/routes/moskva-tula': illustration('moskva-tula', 'Семья с дорожными сумками у минивэна среди уютных старых улиц Тулы', 2),
  '/routes/moskva-ryazan': illustration('moskva-ryazan', 'Путешественники с чемоданами у минивэна на фоне зелёной Рязани'),
  '/routes/moskva-kaluga': illustration('moskva-kaluga', 'Родители с ребёнком и чемоданами у минивэна после поездки в Калугу'),
  '/routes/moskva-kostroma': illustration('moskva-kostroma', 'Семья с багажом рядом с минивэном на тихой исторической улице Костромы', 2),
  '/routes/nizhniy-novgorod-moskva': illustration('nizhniy-novgorod-moskva', 'Компания с дорожными чемоданами у минивэна на фоне Москвы'),
  '/routes/krasnodar-simferopol': illustration('krasnodar-simferopol', 'Путешественники с багажом у минивэна в залитом солнцем южном городе'),
  '/routes/rostov-anapa': illustration('rostov-anapa', 'Родители с дочерью и чемоданами рядом с минивэном среди сосен и морского света Анапы'),
  '/routes/chelyabinsk-ekaterinburg': illustration('chelyabinsk-ekaterinburg', 'Небольшая компания с дорожными сумками у минивэна на фоне городского пруда Екатеринбурга'),
  '/routes/nizhniy-novgorod-kazan': illustration('nizhniy-novgorod-kazan', 'Мама, папа и дочь с чемоданами у минивэна в старом квартале Казани'),
  '/routes/moskva-suzdal': illustration('moskva-suzdal', 'Пара и их взрослая дочь с багажом у минивэна среди деревянных домов Суздаля'),
  '/routes/krasnodar-sochi': illustration('krasnodar-sochi', 'Семья с двумя детьми и чемоданами у светлого минивэна среди субтропической зелени Сочи'),
  '/routes/krasnodar-novorossiysk': illustration('krasnodar-novorossiysk', 'Компания друзей с дорожными сумками у минивэна на фоне бухты Новороссийска'),
  '/routes/ekaterinburg-tyumen': illustration('ekaterinburg-tyumen', 'Мама, сын и бабушка у минивэна на фоне уютной улицы Тюмени'),
  '/routes/samara-kazan': illustration('samara-kazan', 'Пара путешественников с багажом у минивэна на фоне речной панорамы Казани'),
  '/routes/spb-petrozavodsk': illustration('spb-petrozavodsk', 'Семья с подростком и рюкзаками у минивэна на фоне Онежского озера в Петрозаводске'),
  '/routes/volgograd-astrakhan': illustration('volgograd-astrakhan', 'Семья с мальчиком у минивэна среди набережной и зелени Астрахани'),
  '/routes/moskva-yaroslavl': illustration('moskva-yaroslavl', 'Родители с двумя детьми и чемоданами у минивэна в историческом Ярославле'),
  '/routes/moskva-vladimir': illustration('moskva-vladimir', 'Пара с дочерью и багажом у минивэна на фоне белокаменного Владимира'),
  '/routes/ekaterinburg-perm': illustration('ekaterinburg-perm', 'Пара путешественников и водитель у минивэна на фоне Камы в Перми'),
  '/routes/ekaterinburg-kurgan': illustration('ekaterinburg-kurgan', 'Мама с дочерью и бабушка с багажом после поездки на минивэне в Курган'),
  '/routes/kazan-nizhniy-novgorod': illustration('kazan-nizhniy-novgorod', 'Семья с двумя детьми у минивэна на фоне речной панорамы Нижнего Новгорода'),
  '/routes/rostov-krasnodar': illustration('rostov-krasnodar', 'Семья с коляской и чемоданами у минивэна рядом с зелёным городским парком Краснодара'),
  '/routes/spb-velikiy-novgorod': illustration('spb-velikiy-novgorod', 'Семья с мальчиком у минивэна перед прогулкой по Великому Новгороду'),
  '/routes/spb-pskov': illustration('spb-pskov', 'Друзья с дорожными сумками у минивэна на фоне речного пейзажа Пскова'),
  '/routes/novosibirsk-tomsk': illustration('novosibirsk-tomsk', 'Путешественники с чемоданами у минивэна на тихой улице с деревянными домами Томска'),
  '/routes/novosibirsk-barnaul': illustration('novosibirsk-barnaul', 'Родители с мальчиком и багажом рядом с минивэном после поездки в Барнаул'),
  '/routes/volgograd-saratov': illustration('volgograd-saratov', 'Старшая пара с внучкой и водитель у минивэна на фоне Волги в Саратове'),
  '/routes/volgograd-elista': illustration('volgograd-elista', 'Компания путешественников у минивэна на фоне степного неба и буддийской архитектуры Элисты'),
  '/airport/led': illustration('led', 'Пара путешественников в плащах встречает водителя у минивэна в Пулково'),
  '/airport/aer': illustration('aer', 'Родители и девочка с летним багажом у минивэна среди южной зелени'),
  '/airport/mrv': illustration('mrv', 'Водитель помогает старшей паре с чемоданами перед поездкой из Минеральных Вод'),
  '/airport/kgd': illustration('kgd', 'Семья с мальчиком и дорожными чемоданами готовится к поездке из Храброво'),
  '/airport/kzn': illustration('kzn', 'Семья с дочерью и водитель у минивэна перед поездкой из аэропорта Казани'),
  '/airport/svx': illustration('svx', 'Небольшая компания с багажом встречается у минивэна в Кольцово'),
  '/airport/ovb': illustration('ovb', 'Родители со школьником и крупным багажом рядом с минивэном в Толмачёво'),
  '/airport/ikt': illustration('ikt', 'Путешественники с рюкзаками и фотосумкой готовятся к поездке из аэропорта Иркутска'),
  '/airport/mmk': illustration('mmk', 'Друзья в тёплых куртках с зимними сумками у минивэна в Мурманске'),
  '/airport/zia': illustration('zia', 'Родители с ребёнком и чемоданами у минивэна в Жуковском'),
  '/service/luggage': illustration('luggage', 'Семья из четырёх человек собирает чемоданы, коробки и коляску в минивэн'),
  '/service/ski-transfer': illustration('ski-transfer', 'Компания у минивэна с чехлами для лыж и сноуборда на зимнем курорте'),
  '/airport/vko': illustration('vko', 'Семья с детьми и чемоданами у минивэна перед поездкой из аэропорта'),
  '/airport/svo': illustration('svo', 'Водитель встречает маму с дочерью у минивэна в аэропорту'),
  '/airport/dme': illustration('dme', 'Две пары с багажом собираются в поездку на минивэне из аэропорта'),
  '/airport/vko/moscow-center': illustration('vko-moscow-center', 'Мама с дочерью и дедушка прибывают на минивэне к городскому отелю'),
  '/airport/svo/moscow-center': illustration('airport-svo-moscow-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — центр Москвы', 2),
  '/airport/svo/moscow-city': illustration('airport-svo-moscow-city', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — Москва-Сити', 2),
  '/airport/svo/vdnh': illustration('airport-svo-vdnh', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — ВДНХ', 2),
  '/airport/svo/podolsk': illustration('airport-svo-podolsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — Подольск', 2),
  '/airport/svo/zelenograd': illustration('airport-svo-zelenograd', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — Зеленоград', 2),
  '/airport/svo/tver': illustration('airport-svo-tver', 'Пассажиры с багажом у минивэна после поездки Аэропорт Шереметьево — Тверь', 2),
  '/airport/led/spb-center': illustration('airport-led-spb-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Пулково — центр СПб', 2),
  '/airport/led/sortavala': illustration('airport-led-sortavala', 'Пассажиры с багажом у минивэна после поездки Аэропорт Пулково — Сортавала', 2),
  '/airport/led/petrozavodsk': illustration('airport-led-petrozavodsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Пулково — Петрозаводск', 2),
  '/airport/led/vyborg': illustration('airport-led-vyborg', 'Пассажиры с багажом у минивэна после поездки Аэропорт Пулково — Выборг', 2),
  '/airport/led/priozersk': illustration('airport-led-priozersk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Пулково — Приозерск', 2),
  '/airport/aer/sochi-center': illustration('airport-aer-sochi-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Сочи (Адлер) — центр Сочи', 2),
  '/airport/aer/krasnaya-polyana': illustration('airport-aer-krasnaya-polyana', 'Пассажиры с багажом у минивэна после поездки Аэропорт Сочи (Адлер) — Красная Поляна', 2),
  '/airport/aer/rosa-khutor': illustration('airport-aer-rosa-khutor', 'Пассажиры с багажом у минивэна после поездки Аэропорт Сочи (Адлер) — Роза Хутор', 2),
  '/airport/dme/moscow-center': illustration('airport-dme-moscow-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Центр Москвы', 2),
  '/airport/dme/podolsk': illustration('airport-dme-podolsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Подольск', 2),
  '/airport/dme/ramenskoe': illustration('airport-dme-ramenskoe', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Раменское', 1),
  '/airport/dme/zhukovskiy': illustration('airport-dme-zhukovskiy', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Жуковский', 1),
  '/airport/dme/stupino': illustration('airport-dme-stupino', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Ступино', 1),
  '/airport/dme/serpukhov': illustration('airport-dme-serpukhov', 'Пассажиры с багажом у минивэна после поездки Аэропорт Домодедово — Серпухов', 1),
  '/airport/vko/moscow-city': illustration('airport-vko-moscow-city', 'Пассажиры с багажом у минивэна после поездки Аэропорт Внуково — Москва-Сити', 2),
  '/airport/vko/odintsovo': illustration('airport-vko-odintsovo', 'Пассажиры с багажом у минивэна после поездки Аэропорт Внуково — Одинцово', 1),
  '/airport/vko/aprelevka': illustration('airport-vko-aprelevka', 'Пассажиры с багажом у минивэна после поездки Аэропорт Внуково — Апрелевка', 1),
  '/airport/vko/balashikha': illustration('airport-vko-balashikha', 'Пассажиры с багажом у минивэна после поездки Аэропорт Внуково — Балашиха', 1),
  '/airport/vko/vnukovo-derevnya': illustration('airport-vko-vnukovo-derevnya', 'Пассажиры с багажом у минивэна после поездки Аэропорт Внуково — Внуково (деревня)', 1),
  '/airport/zia/moscow-center': illustration('airport-zia-moscow-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Жуковский — Центр Москвы', 1),
  '/airport/zia/zhukovskiy-city': illustration('airport-zia-zhukovskiy-city', 'Пассажиры с багажом у минивэна после поездки Аэропорт Жуковский — Жуковский (город)', 1),
  '/airport/zia/ramenskoe': illustration('airport-zia-ramenskoe', 'Пассажиры с багажом у минивэна после поездки Аэропорт Жуковский — Раменское', 1),
  '/airport/zia/elektrostal': illustration('airport-zia-elektrostal', 'Пассажиры с багажом у минивэна после поездки Аэропорт Жуковский — Электросталь', 1),
  '/airport/kzn/kazan-center': illustration('airport-kzn-kazan-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Казань — Центр Казани', 1),
  '/airport/kzn/innopolis': illustration('airport-kzn-innopolis', 'Пассажиры с багажом у минивэна после поездки Аэропорт Казань — Иннополис', 1),
  '/airport/kzn/zelenodolsk': illustration('airport-kzn-zelenodolsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Казань — Зеленодольск', 1),
  '/airport/kzn/bolgar': illustration('airport-kzn-bolgar', 'Пассажиры с багажом у минивэна после поездки Аэропорт Казань — Болгар', 1),
  '/airport/svx/ekaterinburg-center': illustration('airport-svx-ekaterinburg-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Екатеринбург (Кольцово) — Центр Екатеринбурга', 1),
  '/airport/svx/verkhnyaya-pyshma': illustration('airport-svx-verkhnyaya-pyshma', 'Пассажиры с багажом у минивэна после поездки Аэропорт Екатеринбург (Кольцово) — Верхняя Пышма', 1),
  '/airport/svx/berezovskiy': illustration('airport-svx-berezovskiy', 'Пассажиры с багажом у минивэна после поездки Аэропорт Екатеринбург (Кольцово) — Берёзовский', 1),
  '/airport/svx/nizhniy-tagil': illustration('airport-svx-nizhniy-tagil', 'Пассажиры с багажом у минивэна после поездки Аэропорт Екатеринбург (Кольцово) — Нижний Тагил', 1),
  '/airport/ovb/novosibirsk-center': illustration('airport-ovb-novosibirsk-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Новосибирск (Толмачёво) — Центр Новосибирска', 1),
  '/airport/ovb/akademgorodok': illustration('airport-ovb-akademgorodok', 'Пассажиры с багажом у минивэна после поездки Аэропорт Новосибирск (Толмачёво) — Академгородок', 1),
  '/airport/ovb/berdsk': illustration('airport-ovb-berdsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Новосибирск (Толмачёво) — Бердск', 1),
  '/airport/ovb/koltsovo': illustration('airport-ovb-koltsovo', 'Пассажиры с багажом у минивэна после поездки Аэропорт Новосибирск (Толмачёво) — Кольцово', 1),
  '/airport/ikt/irkutsk-center': illustration('airport-ikt-irkutsk-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Иркутск — Центр Иркутска', 1),
  '/airport/ikt/listvyanka': illustration('airport-ikt-listvyanka', 'Пассажиры с багажом у минивэна после поездки Аэропорт Иркутск — Листвянка', 1),
  '/airport/ikt/shelekhov': illustration('airport-ikt-shelekhov', 'Пассажиры с багажом у минивэна после поездки Аэропорт Иркутск — Шелехов', 1),
  '/airport/ikt/angarsk': illustration('airport-ikt-angarsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Иркутск — Ангарск', 1),
  '/airport/mmk/murmansk-center': illustration('airport-mmk-murmansk-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Мурманск — Центр Мурманска', 1),
  '/airport/mmk/teriberka': illustration('airport-mmk-teriberka', 'Пассажиры с багажом у минивэна после поездки Аэропорт Мурманск — Териберка', 1),
  '/airport/mmk/kirovsk': illustration('airport-mmk-kirovsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Мурманск — Кировск', 1),
  '/airport/mmk/apatity': illustration('airport-mmk-apatity', 'Пассажиры с багажом у минивэна после поездки Аэропорт Мурманск — Апатиты', 1),
  '/airport/mrv/kislovodsk': illustration('airport-mrv-kislovodsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Минеральные Воды — Кисловодск', 1),
  '/airport/mrv/pyatigorsk': illustration('airport-mrv-pyatigorsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Минеральные Воды — Пятигорск', 1),
  '/airport/mrv/essentuki': illustration('airport-mrv-essentuki', 'Пассажиры с багажом у минивэна после поездки Аэропорт Минеральные Воды — Ессентуки', 1),
  '/airport/mrv/zheleznovodsk': illustration('airport-mrv-zheleznovodsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Минеральные Воды — Железноводск', 1),
  '/airport/kgd/kaliningrad-center': illustration('airport-kgd-kaliningrad-center', 'Пассажиры с багажом у минивэна после поездки Аэропорт Калининград — Центр Калининграда', 1),
  '/airport/kgd/svetlogorsk': illustration('airport-kgd-svetlogorsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Калининград — Светлогорск', 1),
  '/airport/kgd/zelenogradsk': illustration('airport-kgd-zelenogradsk', 'Пассажиры с багажом у минивэна после поездки Аэропорт Калининград — Зеленоградск', 1),
  '/airport/kgd/yantarniy': illustration('airport-kgd-yantarniy', 'Пассажиры с багажом у минивэна после поездки Аэропорт Калининград — Янтарный', 1),
  '/routes/kazan-samara': illustration('kazan-samara', 'Семья рядом с минивэном на фоне Волги после поездки в Самару'),
  '/routes/tyumen-ekaterinburg': illustration('tyumen-ekaterinburg', 'Компания у минивэна рассматривает карту на фоне городского пруда'),
  '/routes/ekaterinburg-chelyabinsk': illustration('ekaterinburg-chelyabinsk', 'Семья с багажом у светлого минивэна на зелёном городском бульваре'),
  '/routes/krasnodar-yalta': illustration('krasnodar-yalta', 'Компания путешественников у минивэна на фоне моря и южных гор'),
  '/destination/karelia/spb-ruskeala': illustration('spb-ruskeala', 'Семья начинает прогулку после поездки на минивэне к мраморному каньону'),
  '/destination/baikal/irkutsk-listvyanka': illustration('irkutsk-listvyanka', 'Путешественники рядом с минивэном любуются Байкалом'),
  '/services/children': illustration('children', 'Родители, мальчик и девочка готовят коляску и багаж к семейной поездке'),
};

export function getJourneyIllustration(path: string) { return journeyIllustrations[path]; }
export function journeySocialImage(path: string) {
  const image = getJourneyIllustration(path);
  return image ? { url: 'https://zakazminivena.ru' + image.src, width: image.width, height: image.height, alt: image.alt } : undefined;
}
